const Invoice = require("./invoice.model");

/* =========================================
   HELPER: CALCULATE ITEMS & TOTAL
========================================= */
const calculateItems = (items = []) => {
  if (!Array.isArray(items) || items.length === 0) {
    throw new Error("At least one item is required");
  }

  let total = 0;

  const updatedItems = items.map((item) => {
    const value = Number(item.value || 0);
    const igstRate = Number(item.igstRate || 0);

    if (!isFinite(value) || !isFinite(igstRate)) {
      throw new Error(`Invalid number in item: ${item.description}`);
    }

    const igstAmount = Number(((value * igstRate) / 100).toFixed(2));
    const totalItem = Number((value + igstAmount).toFixed(2));
    total += totalItem;

    return {
      description: item.description,
      hsn: item.hsn || "",
      value,
      igstRate,
      igstAmount,
      total: totalItem,
    };
  });

  return { updatedItems, total: Number(total.toFixed(2)) };
};

/* =========================================
   CREATE INVOICE
   (invoiceNumber auto-generated by schema middleware)
========================================= */
exports.createInvoice = async (body) => {
  if (!body.clientId) throw new Error("Client is required");
  if (!body.items || !body.items.length) throw new Error("At least one item is required");

  const { updatedItems, total } = calculateItems(body.items);

  const invoice = await Invoice.create({
    ...body,
    items: updatedItems,
    totalAmount: total,
  });

  return invoice;
};

/* =========================================
   GET ALL INVOICES (PAGINATION + SEARCH)
========================================= */
exports.getAllInvoices = async ({ page = 1, limit = 10, search = "" }) => {
  const query = {};
  if (search) {
    query.invoiceNumber = { $regex: search, $options: "i" };
  }

  const skip = (page - 1) * limit;

  const [data, total] = await Promise.all([
    Invoice.find(query)
      .populate("clientId")
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit),
    Invoice.countDocuments(query),
  ]);

  return {
    data,
    total,
    page,
    pages: Math.ceil(total / limit),
  };
};

/* =========================================
   GET SINGLE INVOICE
========================================= */
exports.getInvoiceById = async (id) => {
  const invoice = await Invoice.findById(id).populate("clientId");

  if (!invoice) throw new Error("Invoice not found");

  return invoice;
};

/* =========================================
   UPDATE INVOICE
========================================= */
exports.updateInvoice = async (id, body) => {
  const invoice = await Invoice.findById(id);
  if (!invoice) throw new Error("Invoice not found");

  let updatedData = { ...body };

  if (body.items) {
    const { updatedItems, total } = calculateItems(body.items);
    updatedData.items = updatedItems;
    updatedData.totalAmount = total;
  }

  const updatedInvoice = await Invoice.findByIdAndUpdate(id, updatedData, {
    new: true,
    runValidators: true,
  });

  return updatedInvoice;
};

/* =========================================
   DELETE INVOICE
========================================= */
exports.deleteInvoice = async (id) => {
  const invoice = await Invoice.findById(id);
  if (!invoice) throw new Error("Invoice not found");

  await Invoice.findByIdAndDelete(id);
  return { message: "Invoice deleted successfully" };
};

/* =========================================
   GET INVOICE DATA FOR PDF
========================================= */
exports.getInvoiceForPDF = async (id) => {
  const invoice = await Invoice.findById(id).populate("clientId");
  if (!invoice) throw new Error("Invoice not found");

  return invoice;
};

/* =========================================
   DOWNLOAD INVOICE PDF
========================================= */

exports.downloadInvoicePDF = async (req, res) => {
  try {
    const { id } = req.params;

    // Fetch invoice
    const invoice = await exports.getInvoiceById(id);

    // Generate PDF
    const element = React.createElement(InvoicePDF, { data: invoice });
    const stream = await ReactPDF.renderToStream(element);

    // Set headers for PDF download
    res.set({
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename=${invoice.invoiceNumber || "invoice"}.pdf`
    });

    // Pipe PDF to response
    stream.pipe(res);

  } catch (err) {
    console.error("PDF DOWNLOAD ERROR:", err);
    res.status(500).json({
      success: false,
      message: err.message || "Internal Server Error"
    });
  }
};